version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: msfaeg-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: msfaeg
    container_name: msfaeg-app
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_TOKEN: ${JWT_TOKEN}
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    command: npm run dev
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:

